site_name: ExpressLRS.RU
site_url: https://expresslrs.ru/
repo_url: https://github.com/ExpressLRS/ExpressLRS/releases/
repo_name: ExpressLRS
theme:
  name: material
  features:
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.instant
  - toc.follow
  - navigation.path
  - navigation.top
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.code.annotation
  - content.code.copy
  language: ru
  logo: assets/images/logotype.svg
  favicon: favicon.ico
  
  palette:
  - media: "(prefers-color-scheme: dark)"
    scheme: default
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
    primary: teal
    accent: blue
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
    primary: teal
    accent: lime   
markdown_extensions:
  - pymdownx.details
  - toc:
      permalink: true
  - admonition
  - attr_list
  - md_in_html

plugins:
 - social 
 - search
#Добавлять новые пункты через тут, названия заданные тут видны на сайте, названия файлов - структура ссылки#
nav:
 - Главная: index.md
 - Инструкции: 
    - Настройка аппаратуры: Manuals/Firmware/Transmitters/tx-prep.md
    - Параметры сборки: Manuals/FlashingOptions.md
    - Прошивка:
      - Передатчики:
        - Внешние передатчики: Manuals/Firmware/Transmitters/Flashing-external-tx.md
        - Внутренние передатчики: Manuals/Firmware/Transmitters/Flashing-internal-tx.md
      - Приемники:
        - Обычные приемники: Manuals/Firmware/Recievers/external-reciever.md
        - SPI приемники: Manuals/Firmware/Recievers/spi-reciever.md
    - Проблемы:
      - Оживление приемников: Manuals/Problems/Unbrick.md
      - Jumper T-Pro: Manuals/Problems/Jumper T-Pro.md
 - Железо: 
   - Приемники: hardware/receivers.md
   - Конвертеры: hardware/converters.md
 - Инфо: Info/index.md